### ISSUE TITLE
Cache protobuf and gtest compilation in Travis build

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#263]
#### Expected behavior

We shouldn't fetch protobuf and gtest from the network and recompile it every time we do a build.

Binary should be cached and the build script should check for their presence in cache.

To cache the files, take a look at the `.travis.yml` file: 

```yml
cache:
  directories:
  - $HOME/.m2
  - $HOME/pulsar-dep
```

Just need to put them in these directories and they will be still around on the next build.
